---
title: "Batch_effects"
author: "Robbe Fonteyn"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(Seurat)
library(ggplot2)
```

# Look into AML1941 CD34 in SAB016, AML1941 CD34 in SAB022

```{r}
# Load the data
AML1941_CD34_SAB016 <- readRDS("../Data/Processed_SCC/PROCESSED/SAB016/SAB016/SAB016_seurat.rds")
AML1941_CD34_SAB022 <- readRDS("../Data/Processed_SCC/PROCESSED/SAB022/SAB022/SAB022_seurat.rds")
```


# ChatGPT code
```{r}
# Merge the donors into a single Seurat object
merged <- merge(AML1941_CD34_SAB016, y = AML1941_CD34_SAB022, add.cell.ids = c("AML1941_CD34_SAB016", "AML1941_CD34_SAB022"), project = "CITEseq")
 
# Normalize and find variable features in the merged object
merged <- NormalizeData(merged)
merged <- FindVariableFeatures(merged)
 
# Scale data and run PCA
merged <- ScaleData(merged)
merged <- RunPCA(merged, npcs = 30)
 
merged$experimentid <- merged$orig.ident
```

```{r}
# Run UMAP
merged <- RunUMAP(merged, reduction = "pca", dims = 1:30)
```
```{r}
DimPlot(merged, reduction = "umap", group.by = "experimentid") + ggtitle("UMAP of AML1941 CD34 in SAB016 and SAB022")

# Save the image
ggsave("../../Graphs/Batch_effects/AML1941_UMAP.png")
```

# Same for  AML1941 LD in SAB017 and SAB023
```{r}
# Load the data
AML1941_LD_SAB017 <- readRDS("../Data/Processed_SCC/PROCESSED/SAB017/SAB017/SAB017_seurat.rds")
AML1941_LD_SAB023 <- readRDS("../Data/Processed_SCC/PROCESSED/SAB023/SAB023/SAB023_seurat.rds")
```

```{r}
# Merge the donors into a single Seurat object
merged <- merge(AML1941_LD_SAB017, y = AML1941_LD_SAB023, add.cell.ids = c("AML1941_LD_SAB017", "AML1941_LD_SAB023"), project = "CITEseq")
 
# Normalize and find variable features in the merged object
merged <- NormalizeData(merged)
merged <- FindVariableFeatures(merged)
 
# Scale data and run PCA
merged <- ScaleData(merged)
merged <- RunPCA(merged, npcs = 30)
 
merged$experimentid <- merged$orig.ident

# Run UMAP
merged <- RunUMAP(merged, reduction = "pca", dims = 1:30)
```

```{r}
DimPlot(merged, reduction = "umap", group.by = "experimentid") + ggtitle("UMAP of AML1941 LD in SAB017 and SAB023")

# Save the image
ggsave("../../Graphs/Batch_effects/AML1941_LD_UMAP.png")
```

# Same for AML1745 LD in SAB018 and SAB025
```{r}
# Load the data
AML1745_LD_SAB018 <- readRDS("../Data/Processed_SCC/PROCESSED/SAB018/SAB018/SAB018_seurat.rds")
AML1745_LD_SAB025 <- readRDS("../Data/Processed_SCC/PROCESSED/SAB025/SAB025/SAB025_Hashtag15_cluster_ADT_seurat.rds")
```

```{r}
# Merge the donors into a single Seurat object
merged <- merge(AML1745_LD_SAB018, y = AML1745_LD_SAB025, add.cell.ids = c("AML1745_LD_SAB018", "AML1745_LD_SAB025"), project = "CITEseq")
 
# Normalize and find variable features in the merged object
merged <- NormalizeData(merged)
merged <- FindVariableFeatures(merged)
 
# Scale data and run PCA
merged <- ScaleData(merged)
merged <- RunPCA(merged, npcs = 30)
 
merged$experimentid <- merged$orig.ident

# Run UMAP
merged <- RunUMAP(merged, reduction = "pca", dims = 1:30)
```

```{r}
DimPlot(merged, reduction = "umap", group.by = "experimentid") + ggtitle("UMAP of AML1745 LD in SAB018 and SAB025")

# Save the image
ggsave("../../Graphs/Batch_effects/AML1745_LD_UMAP.png")
```

# Same for AML1745 CD34 in SAB019 and SAB024
```{r}
# Load the data
AML1745_CD34_SAB019 <- readRDS("../Data/Processed_SCC/PROCESSED/SAB019/SAB019_reseq/SAB019_reseq_Hashtag3_cluster_ADT_seurat.rds")
AML1745_CD34_SAB024 <- readRDS("../Data/Processed_SCC/PROCESSED/SAB024/SAB024/SAB024_Hashtag15_cluster_ADT_seurat.rds")
```

```{r}
# Merge the donors into a single Seurat object
merged <- merge(AML1745_CD34_SAB019, y = AML1745_CD34_SAB024, add.cell.ids = c("AML1745_CD34_SAB019", "AML1745_CD34_SAB024"), project = "CITEseq")
 
# Normalize and find variable features in the merged object
merged <- NormalizeData(merged)
merged <- FindVariableFeatures(merged)
 
# Scale data and run PCA
merged <- ScaleData(merged)
merged <- RunPCA(merged, npcs = 30)
 
merged$experimentid <- merged$orig.ident

# Run UMAP
merged <- RunUMAP(merged, reduction = "pca", dims = 1:30)
```

```{r}
DimPlot(merged, reduction = "umap", group.by = "experimentid") + ggtitle("UMAP of AML1745 CD34 in SAB019 and SAB024")

# Save the image
ggsave("../../Graphs/Batch_effects/AML1745_CD34_UMAP.png")
```










