
```{r}
library(harmony)
library(Seurat)
library(dplyr)
library(cowplot)
library(ggplot2)
```

```{r}
# Load the SAB
setwd("C:/Users/Robbe Fonteyn/OneDrive - UGent/AJ 2024-2025/Master's_Dissertation/AML-CITEseq/Data")
SAB <- readRDS("SAB_slimmed_final_harmony.rds")
```

```{r}
set.seed(2410)
SAB <- RunHarmony(SAB, group.by.vars = c("Patient", "orig.ident", "Sorting", "day"), reduction.use = "pca", reduction.save = "RNA_harmony")
SAB <- RunUMAP(SAB, reduction = "RNA_harmony", dims = 1:30, reduction.name = "RNA_harmony_umap")
SAB <- FindNeighbors(SAB, dims = 1:20, reduction= "RNA_harmony", graph.name = c("RNA_harmony_nn", "RNA_harmony_snn"))
SAB <- FindClusters(SAB, resolution = 0.5, graph = "RNA_harmony_snn", cluster.name = "RNA_harmony_clusters")
```

```{r}
ElbowPlot(SAB, reduction = "RNA_harmony")
```

```{r}
p1 <- DimPlot(SAB, reduction = "RNA_harmony_umap", group.by = "predicted.celltype.l2", raster = FALSE, label = TRUE) + NoLegend()
p2 <- DimPlot(SAB, reduction = "RNA_harmony_umap", group.by = "Triana_celltype", label = TRUE, raster = FALSE) + NoLegend()
plot_grid(p1, p2)
```

```{r}
# Assign cluster majority cell type based on Triana annotation
cluster_col <- "RNA_harmony_clusters"
celltype_col <- "Triana_celltype"

SAB@meta.data[[cluster_col]] <- as.factor(SAB@meta.data[[cluster_col]])
SAB@meta.data[[celltype_col]] <- as.factor(SAB@meta.data[[celltype_col]])

cluster_majority <- SAB@meta.data %>%
  group_by(cluster = .data[[cluster_col]]) %>%
  count(celltype = .data[[celltype_col]]) %>%
  slice_max(n, n = 1, with_ties = FALSE) %>%
  ungroup()

lookup <- setNames(cluster_majority$celltype, cluster_majority$cluster)
SAB@meta.data$Triana_cluster_majority_celltype <- lookup[as.character(SAB@meta.data[[cluster_col]])]
```

```{r}
# Assign Azimuth predicted cell type l2 based on majority in each cluster
celltype_col <- "predicted.celltype.l2"
SAB@meta.data[[celltype_col]] <- as.factor(SAB@meta.data[[celltype_col]])

cluster_majority <- SAB@meta.data %>%
  group_by(cluster = .data[[cluster_col]]) %>%
  count(celltype = .data[[celltype_col]]) %>%
  slice_max(n, n = 1, with_ties = FALSE) %>%
  ungroup()

lookup <- setNames(cluster_majority$celltype, cluster_majority$cluster)
SAB@meta.data$Azimuth_cluster_majority_celltype_l2 <- lookup[as.character(SAB@meta.data[[cluster_col]])]
```

```{r}
# Assign Azimuth predicted cell type l1 based on majority in each cluster
celltype_col <- "predicted.celltype.l1"
SAB@meta.data[[celltype_col]] <- as.factor(SAB@meta.data[[celltype_col]])

cluster_majority <- SAB@meta.data %>%
  group_by(cluster = .data[[cluster_col]]) %>%
  count(celltype = .data[[celltype_col]]) %>%
  slice_max(n, n = 1, with_ties = FALSE) %>%
  ungroup()

lookup <- setNames(cluster_majority$celltype, cluster_majority$cluster)
SAB@meta.data$Azimuth_cluster_majority_celltype_l1 <- lookup[as.character(SAB@meta.data[[cluster_col]])]
```

```{r}
DimPlot(SAB, reduction = "RNA_harmony_umap", group.by = "RNA_harmony_clusters",label =TRUE, raster = FALSE) + NoLegend()
DimPlot(SAB, reduction = "RNA_harmony_umap", group.by = "Azimuth_cluster_majority_celltype_l1", label = TRUE, raster = FALSE)
DimPlot(SAB, reduction = "RNA_harmony_umap", group.by = "Triana_cluster_majority_celltype", label = TRUE, raster = FALSE) + NoLegend()
DimPlot(SAB, reduction = "RNA_harmony_umap", group.by = "Azimuth_cluster_majority_celltype_l2", label = TRUE, raster = FALSE)
```
# Check counts specific per cluster
```{r}
# Settings
cluster_col <- "RNA_harmony_clusters"
celltype_col <- "predicted.celltype.l2"

# Prepare data
SAB@meta.data[[cluster_col]] <- as.factor(SAB@meta.data[[cluster_col]])
SAB@meta.data[[celltype_col]] <- as.factor(SAB@meta.data[[celltype_col]])

# Count cells per cluster and cell type
cluster_counts <- SAB@meta.data %>%
  group_by(cluster = .data[[cluster_col]]) %>%
  count(celltype = .data[[celltype_col]]) %>%
  ungroup()

cluster_counts %>% 
  filter(cluster == 14) %>% 
  arrange(desc(n))
```


```{r}
#Save the Seurat object with Harmony embeddings
saveRDS(SAB, file = "SAB_Harmony_new.rds")
```

