---
title: "Untitled"
author: "Robbe Fonteyn"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(Seurat)
library(dplyr)
library(ggplot2)
library(ggrepel)
```

```{r}
setwd("C:/Users/Robbe Fonteyn/OneDrive - UGent/AJ 2024-2025/Master's_Dissertation/Results/Differential_expression/NPM1vsOthers")
# Read in data
markers_disease <- read.csv("DE_Genetics_MutatedNPM1_vs_Others_wilcox_limma.csv", header = TRUE, sep = ",")
#rename column X to gene
colnames(markers_disease)[1] <- "gene"
```

```{r}
# Get top 50 genes with smallest adjusted p-values
top_genes <- markers_disease %>%
  arrange(p_val_adj) %>%
  head(50)

# Volcano plot with top genes labeled
volcano_plot <- ggplot(markers_disease, aes(x = avg_log2FC, y = -log10(p_val_adj))) +
  geom_point(aes(color = p_val_adj < 0.05), alpha = 0.6) +
  geom_text_repel(
    data = top_genes,
    aes(label = gene),
    size = 3,
    max.overlaps = 900
  ) +
  scale_color_manual(values = c("black", "red")) +
  theme_minimal() +
  xlab("Log2 Fold Change") +
  ylab("-Log10 Adjusted P-value") +
  ggtitle("Volcano Plot of DE Genes (Mutated NPM1 vs others)") +
  theme_minimal() +
  theme(plot.background = element_rect(fill = "white", color = NA))

volcano_plot
```

```{r}
setwd("C:/Users/Robbe Fonteyn/OneDrive - UGent/AJ 2024-2025/Master's_Dissertation/Results/Differential_expression/NPM1vsOthers")
ggsave("VolcanoPlot_MutatedNPM1_vs_Others_top50_genes.png", width = 8, height = 6, dpi = 600, units = "in")
```


```{r}
# Gene set enrichment analysis
#install.packages("BiocManager")
#BiocManager::install(c("clusterProfiler", "org.Hs.eg.db", "enrichplot"))
```

```{r}
library(clusterProfiler)
library(org.Hs.eg.db)

# Drop NAs and rank genes
gene_list <- markers_disease %>%
  filter(!is.na(avg_log2FC)) %>%
  arrange(desc(avg_log2FC)) %>%
  distinct(gene, .keep_all = TRUE) %>%
  mutate(entrez = mapIds(
    org.Hs.eg.db,
    keys = gene,
    column = "ENTREZID",
    keytype = "SYMBOL",
    multiVals = "first"
  )) %>%
  filter(!is.na(entrez)) %>%
  distinct(entrez, .keep_all = TRUE)

# Convert gene symbols to ENTREZ IDs
gene_list$entrez <- mapIds(org.Hs.eg.db,
                           keys = gene_list$gene,
                           column = "ENTREZID",
                           keytype = "SYMBOL",
                           multiVals = "first")

# Prepare ranked named vector
ranked_genes <- setNames(gene_list$avg_log2FC, gene_list$entrez)
ranked_genes <- sort(ranked_genes, decreasing = TRUE)

```


```{r}
gsea_results <- gseGO(
  geneList = ranked_genes,
  OrgDb = org.Hs.eg.db,
  keyType = "ENTREZID",
  ont = "BP",
  minGSSize = 10,
  maxGSSize = 500,
  pvalueCutoff = 0.05,
  verbose = TRUE,
  eps= 0
)
```

```{r}
library(enrichplot)

# Enrichment plot of top pathway
gseaplot2(gsea_results, , geneSetID = 1)

# Dotplot of top 10
dotplot(gsea_results) + ggtitle("Top Enriched GO Terms (GSEA) in Mutated NPM1 vs Others")

```
```{r}
setwd("C:/Users/Robbe Fonteyn/OneDrive - UGent/AJ 2024-2025/Master's_Dissertation/Results/Differential_expression/NPM1vsOthers")
ggsave("GSEA_plot_MutatedNPM1_vs_Others.png", width = 8, height = 6, dpi = 600, units = "in")
```


```{r}
gsea_table <- as.data.frame(gsea_results)
write.csv(gsea_table, "GSEA_GO_BP_AML_vs_HC_(Disease).csv", row.names = FALSE)
```

