---
title: "Annotation_Azimuth"
author: "Robbe Fonteyn"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
#if (!requireNamespace('remotes', quietly = TRUE)) {install.packages('remotes')}
remotes::install_github('satijalab/azimuth', ref = 'master')


#packages <- c("Rhtslib", "GenomicAlignments", "Rsamtools", "rtracklayer", "GenomicFeatures", "CNEr", "BSgenome", "ensembldb", "TFBSTools", "EnsDb.Hsapiens.v86", "BSgenome.Hsapiens.UCSC.hg38")

#for (package in packages){
#    if (!requireNamespace(package, quietly = TRUE)) {BiocManager::install(package)}}
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Seurat)
library(Azimuth)
library(SeuratData)
library(patchwork)
```

```{r}
getwd()
filename <- "../Data/Processed_SCC/PROCESSED/SAB001/SAB001_reseq/SAB001_reseq_seurat.rds"
data <- readRDS(filename)
```

```{r}
data <- RunAzimuth(data, reference="bonemarrowref")
```

```{r}
p1 <- DimPlot(data, group.by = "predicted.celltype.l2", label = TRUE, label.size = 3)
p1
```

```{r}
p2 <- DimPlot(data, group.by = "predicted.celltype.l1", label = TRUE)
p2
```


```{r}
data <- NormalizeData(data)
Idents(data) <- "predicted.celltype.l2"

p1 <- FeaturePlot(data, features = "CCR7")
p2 <- FeaturePlot(data, features = "FCGR3A")
p3 <- VlnPlot(data, features = "AXL", group.by = "predicted.celltype.l2", idents = c("ASDC",
    "pDC", "cDC1", "cDC2"))

p1 + p2 + p3 + plot_layout(ncol = 2)
```

```{r}
FeaturePlot(data, features = c("AVP", "KLF1", "MPO", "VWF"))
```

