
```{r}
# Load necessary libraries
library(Seurat)
library(ggplot2)
library(DESeq2)
library(dplyr)
library(presto)

# Define function to save plots with high resolution
save_high_res_plot <- function(plot, filename) {
  ggsave(filename, plot = plot, width = 8, height = 6, dpi = 300, units = "in")
}

message(paste("Loading merged object..."))
path <- "SAB_Full_with_patient.rds"
SAB <- readRDS(path)
```

```{r}
cd34_positive <- subset(SAB, subset = Sorting == "CD34+")
```


```{r}
DefaultAssay(cd34_positive) <- "ADT"

# Check distribution
VlnPlot(cd34_positive, features = "CD123")

# Subset to CD123 low/negative (adjust threshold)
lsc_like <- subset(cd34_positive, subset = CD123 < 1)
```

```{r}
DefaultAssay(lsc_like) <- "RNA"

lsc_genes <- c("HOXA9", "MEIS1", "GPR56", "MN1", "HMGA2", "CDK6", "SPINK2")

lsc_like <- AddModuleScore(lsc_like, features = list(lsc_genes), name = "LSC_Score")

FeaturePlot(lsc_like, features = "LSC_Score1")
```

```{r}
lsc_like$Is_LSC <- "LSC"
cd34_positive$Is_LSC <- ifelse(Cells(cd34_positive) %in% Cells(lsc_like), "LSC", "non-LSC")

# Add metadata back
cd34_positive$Is_LSC <- factor(cd34_positive$Is_LSC, levels = c("non-LSC", "LSC"))

# Compare Genetics by LSC status
table(cd34_positive$Is_LSC, cd34_positive$Genetics)

```

