---
title: "metrics"
author: "Katrien Quintelier"
date: "2024-05-22"
output: html_document
---

```{r init, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, root.dir="C:/Users/Robbe Fonteyn/OneDrive - UGent/AJ 2024-2025/Master's_Dissertation/Github_Repo/AML-CITEseq/Data/Metrics_summary")
```

```{r}
library(ggplot2)
```

# Sequencing metrics
## Get all metrics in 1 table
### Overview data
```{r}
all_data <- list("CITESeq" = setdiff(sprintf("SAB%03d", 1:35), "SAB034"))
all_data

all_data_reseq <- list("CITESeq_reseq" = sprintf("SAB%03d", c(1:10, 13:14, 19)))
all_data_reseq
```

### Make data frames
```{r, echo=FALSE, message=FALSE, warning=FALSE}
setwd("C:/Users/Robbe Fonteyn/OneDrive - UGent/AJ 2024-2025/Master's_Dissertation/Github_Repo/AML-CITEseq/Data/Metrics_summary")
read_metrics <- function(assay, all_data, file_extension) {
  all_metrics <- list()
  
  for (ID in all_data[[assay]]) {
    current_filename <- paste0(ID, file_extension)
    print(paste("Reading in file:", current_filename))
    
    csv <- read.csv(current_filename, check.names = FALSE)
    
    if (is.null(all_metrics[[assay]])) {
      all_metrics[[assay]] <- matrix(NA,
                                      nrow = length(all_data[[assay]]), 
                                      ncol = ncol(csv),
                                      dimnames = list(all_data[[assay]], colnames(csv)))
    }
    
    all_metrics[[assay]][ID, ] <- unlist(csv)
    cat("Done Reading File\n\n")
  }
  
  all_metrics[[assay]] <- data.frame(all_metrics[[assay]], check.names = FALSE)
  
  return(all_metrics)
}

metrics_CITESeq <- read_metrics("CITESeq", all_data, "_metrics_summary.csv")
metrics_CITESeq_reseq <- read_metrics("CITESeq_reseq", all_data_reseq, "_reseq_metrics_summary.csv")

```

### Clean up data frames
```{r}
metrics_CITESeq$CITESeq <- data.frame(sapply(metrics_CITESeq$CITESeq, function(x) as.numeric(gsub("%", "", gsub(",", "", x)))), check.names = FALSE)
metrics_CITESeq$CITESeq$ID <- as.factor(all_data$CITESeq)
metrics_CITESeq$CITESeq$Day <- as.factor(rep(c("Day1", "Day2", "Day3"), times = c(7, 12, 15)))

metrics_CITESeq_reseq$CITESeq_reseq <- data.frame(sapply(metrics_CITESeq_reseq$CITESeq_reseq, function(x) as.numeric(gsub("%", "", gsub(",", "", x)))), check.names = FALSE)
metrics_CITESeq_reseq$CITESeq_reseq$ID <- as.factor(all_data_reseq$CITESeq_reseq)
metrics_CITESeq_reseq$CITESeq_reseq$Day <- as.factor(rep(c("Day1", "Day2"), times = c(7, 6)))
```

## Figures
```{r}
setwd("C:/Users/Robbe Fonteyn/OneDrive - UGent/AJ 2024-2025/Master's_Dissertation/Github_Repo/AML-CITEseq/Graphs")
make_plots <- function(assay, all_data, all_metrics, colors) {
  pdf(paste0("metrics_", assay, ".pdf"), width = length(all_data[[assay]]) / 2 + 2)
  
  for (feature in colnames(all_metrics[[assay]])) {
    p <- ggplot(all_metrics[[assay]], aes(x = ID, y = !!sym(feature))) +
      geom_segment(aes(xend = ID, yend = 0)) +
      geom_point(size = 4, aes(color = Day)) +
      scale_color_manual(values = colors) +
      theme_minimal() +
      xlab("")
    
    print(p)
  }
  
  dev.off()
}

colors_3_days <- c("#ff006e", "#3a86ff", "#00ff00")
colors_2_days <- c("#ff006e", "#3a86ff")

#make_plots("CITESeq", all_data, all_metrics, colors_3_days)
make_plots("CITESeq_reseq", all_data_reseq, metrics_CITESeq_reseq, colors_2_days)

```
