
```{r}
# Load libraries
library(Seurat)
library(ggplot2)
```

```{r}
# Load in the object
setwd("C:/Users/Robbe Fonteyn/OneDrive - UGent/AJ 2024-2025/Master's_Dissertation/AML-CITEseq/Data")
SAB <- readRDS("SAB_slimmed_final.rds")
```

```{r}
# Subset the object into LD and CD34+ sorting
SAB_LD <- subset(SAB, subset = Sorting == "L/D")
SAB_CD34 <- subset(SAB, subset = Sorting == "CD34+")
```

```{r}
rm(SAB)
SAB_CD34 <- NormalizeData(SAB_CD34)
SAB_CD34 <- FindVariableFeatures(SAB_CD34)
SAB_CD34 <- ScaleData(SAB_CD34)
SAB_CD34 <- RunPCA(SAB_CD34)
SAB_CD34 <- RunUMAP(SAB_CD34, dims = 1:30)
SAB_CD34 <- FindNeighbors(SAB_CD34, dims = 1:30)
SAB_CD34 <- FindClusters(SAB_CD34)
```

```{r}
rm(SAB)
SAB_LD <- NormalizeData(SAB_LD)
SAB_LD <- FindVariableFeatures(SAB_LD)
SAB_LD <- ScaleData(SAB_LD)
SAB_LD <- RunPCA(SAB_LD)
SAB_LD <- RunUMAP(SAB_LD, dims = 1:30)
SAB_LD <- FindNeighbors(SAB_LD, dims = 1:30)
SAB_LD <- FindClusters(SAB_LD)
```

```{r}
# Make a new meta.data column to assign a predicted celltype to each cluster by majority presence in that cluster
# Set clustering column
cluster_col <- "RNA_snn_res.0.8"  # adjust if your column name is different
celltype_col <- "Triana_celltype"  # adjust to your actual column

# Ensure these are factors
SAB_LD@meta.data[[cluster_col]] <- as.factor(SAB_LD@meta.data[[cluster_col]])
SAB_LD@meta.data[[celltype_col]] <- as.factor(SAB_LD@meta.data[[celltype_col]])

# Majority vote per cluster
library(dplyr)
cluster_majority <- SAB_LD@meta.data %>%
  group_by(cluster = .data[[cluster_col]]) %>%
  count(celltype = .data[[celltype_col]]) %>%
  slice_max(n, n = 1, with_ties = FALSE) %>%
  ungroup()

# Merge with full metadata
lookup <- setNames(cluster_majority$celltype, cluster_majority$cluster)
SAB_LD@meta.data$Triana_cluster_majority_celltype <- lookup[as.character(SAB_LD@meta.data[[cluster_col]])]
```

```{r}
setwd("C:/Users/Robbe Fonteyn/OneDrive - UGent/AJ 2024-2025/Master's_Dissertation/AML-CITEseq/Data")
saveRDS(SAB_CD34, file = "SAB_CD34.rds")
saveRDS(SAB_LD, file = "SAB_LD.rds")
```
